export {default as App} from './app/app'
export {default as Home} from './home/home'
export {default as About} from './about/about'

export {default as Announcements} from './announcements/announcements'
export {default as ListPosts} from './list-posts/list-posts'
export {default as ViewPost} from './view-post/view-post'
export {default as Notes} from './notes/notes'
export {default as Team} from './team/team'
export {default as Alexa} from './alexa/alexa'
